[package]
name = "ring_buf"
version = "0.1.0"
authors = ["Henk Dieter Oordt <henkdieter@oordt.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.6.2"
nb = "0.1.2"
